spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/artviewer_gallery?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&useSSL=false
    username: root
    password: root
    initialSize: 5
    minIdle: 5
    maxActive: 20
    maxWait: 60000
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: SELECT 1 FROM DUAL
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxPoolPreparedStatementPerConnectionSize: 20
    filters: stat,wall,log4j
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    joda-date-time-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  http:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
  mvc:
    servlet:
      load-on-startup: 1
  redis:
    host: localhost
    port: 6379
  mail:
    default-encoding: UTF-8
    host: smtp.163.com
    username: xxx@163.com
    password: xxx
    protocol: smtp
    test-connection: false
  thymeleaf:
     cache: false
     prefix: classpath:/templates/
     suffix: .html
     encoding: UTF-8
     content-type: text/html
     mode: HTML5
  resources:
    chain:
      strategy:
        content:
          enabled: true
          paths: /**
  freemarker:
    charset: UTF-8
    content-type: text/html
    cache: true
    suffix: .ftl
    template-loader-path: classpath:/templates/
    request-context-attribute: request
mybatis:
  type-aliases-package: cn.artviewer.gallery.model
  mapper-locations: classpath:/mybatis-mappers/*
files:
  path: ${file-path:d:/files}
logging:
  config: classpath:logback-gallery.xml
log:
  level:
    root: info
    my: debug
  file: logs/gallery.log
  maxsize: 30MB
token:
  expire:
    seconds: 86400
server:
  port: 8086
pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: count=countSql



